### ISSUE TITLE
Sigma level for models with input pixels between 0 and 1

### ISSUE THREAD

**Issue by Zephyrasgit** [locuslab/smoothing#6]
Hi, may I know how I can use the certify method if my images need to be within [0, 1] before input into my classifier? Specifically, my model takes in an input image divided by 255 and classifies that. Should I set sigma=0.5 or sigma=0.5/255 as the sigma to the Gaussian noise injected into my input image?

**Comment by jmcohen** [comment]
It should be sigma = 0.5.  (Yeah, it's a lot of noise)

**Comment by Zephyrasgit** [comment]
Thanks for the reply! I see. My problem is that my certified accuracy is as low as 0.1. My original accuracy is close to 0.8. Do you reckon that it is because my classifier had not seen enough noisy images? if so, may I know how extensive should I go about training the base classifier with the noisy images? Can you guide me on how you did it with your base classifier?

**Comment by jmcohen** [comment]
Hmm 0.1 seems very low.  Are you training the base classifier with the same level of noise that you are later using for smoothing?   This is the script I used to train with noise: https://github.com/locuslab/smoothing/blob/master/code/train.py.   The exact commands I ran are here: https://github.com/locuslab/smoothing/blob/master/experiments.MD

**Comment by Zephyrasgit** [comment]
Yeah, 0.1 is about the standard of random guessing I would presume. Yes, I am training the base classifier with sigma=0.5 of noise, which is the sigma I use for RS as well. If you wouldn't mind, can I take more time to triple check my code to ensure there is no error, rerun RS on newly generated dataset with Gaussian noise and get back to you again? Hopefully this is due to errors in my code.

**Comment by Zephyrasgit** [comment]
Ah, I have my results and it turned out to be an error in my own codes. Thanks a lot, pardon me for my clumsiness.
